spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: warn
    me.pexcn.demo: info
    tk.mybatis.spring.mapper.ClassPathMapperScanner: error
    org.mybatis.spring.mapper.ClassPathMapperScanner: error
