spring:
  profiles:
    active: dev

server:
  port: 80

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.pexcn.demo.entity

mapper:
  identity: MYSQL
  mappers: me.pexcn.demo.base.BaseMapper
  before: true
  safe-update: true
  safe-delete: true

pagehelper:
  auto-dialect: true
  helper-dialect: mysql
  dialect-alias:
    alias[0]: com.github.pagehelper.dialect.helper.MySqlDialect
  reasonable: true
  support-methods-arguments: true

# workaround only, more: https://github.com/springfox/springfox/issues/2265#issuecomment-413286451
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
